public enum Operand {
	VARIABLE,
	WIDE_VARIABLE,
	TYPE,
	BYTE_IMMEDIATE,
	FIELD,
	BRANCH_OFFSET,
	WIDE_BRANCH_OFFSET,
	DYNAMIC,
	ZERO_BYTE,
	COUNT,
	INTERFACEMETHODREF,
	METHODREF,
	CONSTANT_INDEX,
	WIDE_CONSTANT_INDEX,
	UNIMPLEMENTED,
	ATYPE,
	SHORT_IMMEDIATE,
	INSTRUCTION,
	PAD_ALIGN_4,
	INT_IMMEDIATE,
	LOOKUPSWITCH_PAIRS,
	TABLESWITCH_OFFSETS;

	public Operand widen() {
		return switch (this) {
			case CONSTANT_INDEX -> WIDE_CONSTANT_INDEX;
			case BRANCH_OFFSET -> WIDE_BRANCH_OFFSET;
			default -> this;
		};
	}
}
